// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-campaign-overview.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_campaign_overview_default = defineTool({
  name: "get_campaign_overview",
  title: "Get Campaign Overview",
  description: "Returns a high-level overview of the Paper Shoes 80 campaign \u2014 80 marathons in 80 days across India to fight plastic pollution.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: [
          "Paper Shoes 80 is an endurance-driven environmental campaign: 80 marathons in 80 days across India.",
          "Mission: turn endurance into environmental action against plastic pollution through school visits, community runs, and clean-ups.",
          "Runners: Matteo, Nagaraju, and Michael.",
          "Framework: Five Pillars of Change \u2014 Symbolic Action, Community Activation, Data & Accountability, Youth Education, Legacy & Systems Change.",
          "Donations: https://gofund.me/62b8c3961",
          "Instagram: https://www.instagram.com/papershoes80",
          "YouTube: https://youtu.be/7zzznw3fGyA"
        ].join("\n")
      }
    ]
  })
});

// src/lib/mcp/tools/get-five-pillars.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var PILLARS = [
  {
    name: "Symbolic Action",
    summary: "The run itself as a visible act of endurance that draws attention to plastic pollution."
  },
  {
    name: "Community Activation",
    summary: "School visits, community runs, and local clean-ups that mobilise people along the route."
  },
  {
    name: "Data & Accountability",
    summary: "Measuring waste collected, people reached, and partners engaged to keep impact transparent."
  },
  {
    name: "Youth Education",
    summary: "Workshops and storytelling with students so the next generation carries the mission forward."
  },
  {
    name: "Legacy & Systems Change",
    summary: "Building lasting partnerships and policy conversations that outlive the 80-day run."
  }
];
var get_five_pillars_default = defineTool2({
  name: "get_five_pillars",
  title: "Get Five Pillars of Change",
  description: "Returns the campaign's Five Pillars of Change framework. Optionally filter by pillar name.",
  inputSchema: {
    pillar: z.string().optional().describe("Optional pillar name to filter (case-insensitive substring match).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ pillar }) => {
    const q = (pillar ?? "").toLowerCase().trim();
    const results = q ? PILLARS.filter((p) => p.name.toLowerCase().includes(q)) : PILLARS;
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { pillars: results }
    };
  }
});

// src/lib/mcp/tools/get-runners.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var RUNNERS = [
  {
    name: "Matteo",
    role: "Endurance runner and campaign co-founder",
    bio: "Italian ultra-runner leading the 80-marathon effort across India."
  },
  {
    name: "Nagaraju",
    role: "Endurance runner",
    bio: "Indian long-distance runner anchoring the campaign's community activations."
  },
  {
    name: "Michael",
    role: "Endurance runner",
    bio: "Runner and storyteller documenting the daily journey."
  }
];
var get_runners_default = defineTool3({
  name: "get_runners",
  title: "Get Runners",
  description: "Returns the runners taking part in the Paper Shoes 80 campaign.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(RUNNERS, null, 2) }],
    structuredContent: { runners: RUNNERS }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "paper-shoes-80-mcp",
  title: "Paper Shoes 80 MCP",
  version: "0.1.0",
  instructions: "Public read-only tools for the Paper Shoes 80 campaign: overview, runners, and the Five Pillars of Change framework. Use these to answer questions about the campaign.",
  tools: [get_campaign_overview_default, get_runners_default, get_five_pillars_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
